# Generated by Django 3.1.7 on 2021-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.IntegerField(choices=[(0, '국어국문학'), (1, '사학'), (2, '철학'), (3, '종교학'), (4, '영미어문'), (5, '미국문화'), (6, '유럽문화'), (7, '중국문화'), (8, '사회학'), (9, '정치외교학'), (10, '심리학'), (11, '국제한국학'), (12, '아트&테크놀로지'), (13, '신문방송학'), (14, '미디어&엔터테인먼트'), (15, '글로벌 한국학'), (16, '수학'), (17, '물리학'), (18, '화학'), (19, '생명과학'), (20, '전자공학'), (21, '화공생명공학'), (22, '컴퓨터공학'), (23, '기계공학'), (24, '경제학'), (25, '경영학'), (26, '커뮤니케이션학')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(0, '재학'), (1, '군휴학'), (2, '일반 휴학'), (3, '졸업'), (4, '교환')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
