name: update djnago server

on:
  push:
    branches:
      - master

jobs:
  pullUpstreamSource:  # job 이름
    name: downstream automation and restart django
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ssh 접속 및 script 실행
        uses: appleboy/ssh-action@master
        with:
          host: 18.190.43.125
          username: ubuntu
          key: ${{ secrets.SGCC_PRIVATE }}
          port: 22
          script: |
            tmux attach -t 0
            cd /home/ubuntu/sgcc_homepage_django
            git pull origin master
            sleep 5
            source venv/bin/activate
            echo yes | python3 manage.py collectstatic
            python3 manage.py makemigrations
            python3 manage.py migrate
            sleep 5
            deactivate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
            echo "done!"